// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eofmdmkpekwmvnoaftnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZm1kbWtwZWt3bXZub2FmdG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTk2MzAsImV4cCI6MjA2MzgzNTYzMH0.N5OW7424ES1jPSD9Ae6OSVNl0Xn1uJsCGIRhoG9zees";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);